### Register an app to the oauth server
POST http://localhost:8081/register
Content-Type: application/x-www-form-urlencoded

name=Test2
&uri=http://localhost:8082
&redirect_success=http://localhost:8082/success
&redirect_error=http://localhost:8082/error

###
GET http://localhost:8081/auth?response_type=code&client_id=client_606c5bfe886e14.91787997&scope=email&state=dskdlnznscxjls

###
GET http://localhost:8081/auth-Oui?client_id=client_606c5bfe886e14.91787997&state=dskdlnznscxjls

###
GET http://localhost:8081/token?grant_type=authorization_code&code=code_60d9bfd35905d&client_id=client_606c5bfe886e14.91787997&client_secret=2ce690b11c94aca36d9ec493d9121f9dbd5c96a5

###
GET http://localhost:8081/token?grant_type=password&username=jdup&password=jdup&client_id=client_606c5bfe886e14.91787997&client_secret=2ce690b11c94aca36d9ec493d9121f9dbd5c96a5

###
GET http://localhost:8081/token?grant_type=client_credentials&client_id=client_606c5bfe886e14.91787997&client_secret=2ce690b11c94aca36d9ec493d9121f9dbd5c96a5

###
GET http://localhost:8081/api
Authorization: Bearer token_60d9c0ad18bd58.24315278